routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::prefix('auth')->namespace("Auth")->group(function () {
//     Route::get('/agent/{agent}', 'AuthController@loginAgent')->name('auth.agent.login')->middleware('signed');
//     Route::get('/customer/{customer}/{application}', 'AuthController@loginCustomer')->name('auth.customer.login')->middleware('signed');

// });


// --------- AGENT -------------------------------------------------------------------------------- //




// --------- ADMIN -------------------------------------------------------------------------------- //





// --------- Customer -------------------------------------------------------------------------------- //


Route::prefix('customer')->namespace("Customer")->name('customer.')->group(function () {
    Route::get('/retrieveFromEmail/{customer}', 'CustomerController@email')->name('email')->middleware('signed');
    Route::get('/{customer}/{application}', 'CustomerController@toComplete')->name('application.complete');//->middleware('can:view,application');
});



// --------- GENERIC ROUTES -------------------------------------------------------------------------------- //


Route::get('admin/login', 'LoginController@showLoginForm')->name('login');



// --------- API ROUTES ------------------------------------------------------------------------------------ //

Route::prefix('api/v1')->namespace("Api")->name('api.v1.')->group(function () {
    Route::get('/validate/email', 'ValidateController@email')->name('validate.email');
    Route::get('/validate/mobile', 'ValidateController@mobile')->name('validate.mobile');
    Route::get('/validate/address', 'ValidateController@address')->name('validate.address');
    Route::post('/validate/address/split', 'ValidateController@addressSplit')->name('validate.address.split');
    
    Route::get('/healthcheck', function () {
        return response()->json([
                'health' => true,
                'version' => 'has',
            ]);
    })->name('health.check');
});


// Route::prefix('health')->group(function () {
//     Route::get('/check', function () {
//         return response()->json([
//             'health' => true,
//         ]);
//     })->name('health.check');
//     Route::get('/version', function () {
//         return response()->json([
//             'verion' => true,
//         ]);
//     })->name('health.version');
    
//     // Route::get('/customer/{customer}/{application}', 'AuthController@loginCustomer')->name('auth.customer.login')->middleware('signed');

//     // Route::get('/agent/{agent}/impersonate', 'AuthController@impersonateAgent')->name('auth.admin.impersonate.agent')->middleware('auth:web');
// });



Route::get('rewards', function () {
    //if (env('APP_ENV') === 'production') {
        return redirect("https://redeem.onthemove.com.au/dashboard");
    // } else {
    //     $url = "https://" . env('APP_ENV') . ".redeem.onthemove.com.au";

    //     return redirect($url);
    // }
})->name('rewardsportal');

app/Models/ApplicationType.php
<?php

namespace OnTheMove\Models;

use OnTheMove\Models\Application;
use Illuminate\Database\Eloquent\Model;

class ApplicationType extends Model
{
    public $timestamps = false;
    protected $guarded = [];

    public function applications()
    {
        return $this->belongsToMany(Application::class, 'application_type_id', 'id');
    }
}

app/Models/Product.php
<?php

namespace OnTheMove\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
  * The products that are sold to customers.
  * Specifically features or constructs of a particular product
  */
class Product extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    // YOLO
    protected $guarded = [];
    // protected $fillable = [
    //     'flowbiz_id',
    //     'name',
    //     'type',
    //     'provider'
    // ];

    public function getNameAttribute($value)
    {
        $value = preg_replace('/^(\d+\s+)?(.*)$/', '$2', $value);

        return trim(preg_replace("/\([^)]+\)|\-\s/", "", $value));
    }

    public function getColorAttribute()
    {
        switch ($this->type) {
            case 'Power':
                return "yellow";
            break;
            case 'Gas':
                return "purple";
            break;
            case 'Water':
                return "azure";
            break;
            case 'Phone':
                return "lime";
            break;
            case 'Internet':
                return "teal";
            break;
            case 'Mobile':
                return "green";
            break;
            case 'Bundle':
                return "gray-dark";
            break;
            default:
                return "blue";
            break;
        }
    }


    public function terms()
    {
        return $this->belongsToMany(ProductTerms::class);
    }
}

app/Http/Controllers/Admin/ApplicationController.php
<?php

namespace OnTheMove\Http\Controllers\Admin;

use Carbon\Carbon;
use OnTheMove\Models\Agent;
use Illuminate\Http\Request;
use OnTheMove\Models\Customer;
use OnTheMove\Models\Application;
use OnTheMove\Models\ExceptionMapping;
use OnTheMove\Models\RealEstateAgency;
use OnTheMove\Http\Controllers\Controller;
use OnTheMove\Models\ApplicationException;

class ApplicationController extends Controller
{
    public function queue(Request $request)
    {
        //$apps = Application::whereNull('agent_id')->get();
        $apps = ApplicationException::all();

        return view('admin.applications.queue', compact('apps'));
    }

    public function match(ApplicationException $exception, Request $request)
    {
        $app = $exception->application;
  
        $agents = Agent::all(['id', 'company_id', 'first_name', 'last_name'])->groupBy('company_id');
        $rea = RealEstateAgency::all(['id', 'company_id', 'company_name', 'group'])->sortBy('company_name')->groupBy('group');
    
        return view("admin.applications.exception_match", compact('exception', 'app', 'rea', 'agents'));
    }

    public function fix(ApplicationException $exception, Request $request)
    {
        $app = $exception->application;
        $method = "fix" . studly_case($exception->type) . "Exception";

        $outcome = $this->{$method}($exception, $request);

        if (! $outcome) {
            flash()->error("Exception mapping couldn't be saved");

            return redirect()->route('admin.application.queue');
        }
        
        if (env('APP_ENV') !== 'local') {
            $exception->delete();
        }
    
        return redirect()->route('admin.application.queue');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $apps = Application::orderBy('created_at', 'desc')->paginate(50);

        return view('admin.applications.index', compact('apps'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \OnTheMove\Models\Application  $app
     * @return \Illuminate\Http\Response
     */
    public function show(Application $app = null, Request $request)
    {
        if (! $app) {
            return $this->showFromFlowbiz($request, $request->value('reference'));
            //$app = $this->appRepo->retrieveFromFlowbiz($request->value('reference'));
        }

        return view('admin.applications.show', compact('app'));
    }

 

    protected function saveExceptionMapping(ApplicationException $exception, $key)
    {
        $mapping = new ExceptionMapping;
        $mapping->payload = $exception->payload;
        $mapping->key = $key;

        // an expection mapping resolved and application exception
        $mapping->resolved()->associate($exception);

        $mapping->save();

        return $mapping;
    }

    protected function fixMissingConnectionDateException(ApplicationException $exception, Request $request)
    {
        $app = $exception->application;

        $app->connection_date = Carbon::createFromFormat('Y-m-d', $request->input('connection_date'))
                                        ->hour(0)
                                        ->minute(0)
                                        ->second(0);
    
        $app->save();
        
        flash()->success('Application Connection Date set to ' . $app->connection_date->format('d/m/Y'));

        return true;
    }

    protected function fixMissingTenantMobileException(ApplicationException $exception, Request $request)
    {
        $pl = json_decode($exception->payload);
        $customer = Customer::find($pl->id);
        $customer->mobile = $request->input('mobile');
        $customer->save();

        flash()->success('Tenant Mobile set to ' . $customer->mobile);

        return true;
    }
    protected function fixMissingTenantEmailException(ApplicationException $exception, Request $request)
    {
        $pl = json_decode($exception->payload);
        $customer = Customer::find($pl->id);

        $customer->email = $request->input('email');
        $customer->save();

        flash()->success('Tenant Email set to ' . $customer->email);

        return true;
    }

    protected function fixMissingPropertyManagerException(ApplicationException $exception, Request $request)
    {
        $agent = Agent::find($request->input('property_manager'));
        $app = $exception->application;

        $app->agent_id = $agent->id;
        $app->save();

        $mapping = $this->saveExceptionMapping($exception, $agent->id);

        flash()->success('Mapped Application Exception to ' . $agent->name);

        return true;
    }


    protected function fixManualApprovalException(ApplicationException $exception, Request $request)
    {
        
        flash()->success('Released app to Flowbiz');

        return true;
    }
}

app/Http/Controllers/Agent/ApplicationController.php
<?php

namespace OnTheMove\Http\Controllers\Agent;

use Log;
use Exception;

use Carbon\Carbon;
use Illuminate\Http\Request;
use OnTheMove\Models\Product;

use OnTheMove\Models\Agent;
use OnTheMove\Models\Customer;
use OnTheMove\Models\Application;
use OnTheMove\Models\ApplicationType;
use OnTheMove\Http\Controllers\Controller;
use Illuminate\Pagination\LengthAwarePaginator;

use OnTheMove\Repositories\ApplicationRepository;
use OnTheMove\Repositories\FlowbizApplicationRepository;

use OnTheMove\Http\Requests\Agent\SearchFormRequest;

class ApplicationController extends Controller
{
    protected $appRepo;
    protected $flowbizAppRepo;

    public function __construct()
    {
        $this->appRepo = new ApplicationRepository();
        $this->flowbizAppRepo = new FlowbizApplicationRepository();
        $this->authorizeResource(Application::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $apps = $this->appRepo->indexAgent();
        $apps = $request->user()->applications()->where('flowbiz_application_status', '!=', 'Void')->paginate(25);
        return view('application.index', compact('apps'));
    }

    public function search(Request $request)
    {
        //$apps = session()->pull('applications.search.results') ?? null;
        $apps = session()->get('applications.search.results') ?? null;
        
        if ($apps) {
            $apps = $this->paginateSerach($request, $apps);
        }

        return view('agent.application.search', compact('apps'));
    }

    /**
     * POST Search
     *
     * @param SearchFormRequest $request    Validated search parameters
     * @return void
     */
    public function searchPost(SearchFormRequest $request)
    {
        try {
            $results = $this->appRepo->search($request->validated());
            session()->put('applications.search.results', $results);
            $apps = $this->paginateSerach($request, $results);

            return view('agent.application.search', compact('apps'));

        } catch (Exception $e) {
            Log::error('Flowbiz API Error: Unable to search', $request->validated());
            flash()->error('Unable to retrieve search results. This has been reported, please try again later.');
            return back()->withInput();
        }
        
    }


    public function showFromFlowbiz(Request $request, $reference)
    {
        try {
            $app = $this->flowbizAppRepo->retrieveFromFlowbiz($reference);
            return redirect()->route('agent.application.show', $app);
            //return view('agent.application.show', compact('app'));

         } catch (Exception $e) {
            Log::error('Flowbiz API Error: Unable to search', ['application' => $reference]);
            flash()->error('Unable to retrieve application. This has been reported, please try again later.');
            return back()->withInput();
        }
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
       $app = session()->get('app') ?? null;
        if ($app) {
            $app = $this->appRepo->get($app);
        }
        //  dd($app, $app->toArray(), $app->renter);
        $types = ApplicationType::all()->pluck('name', 'id');
        $pms = Agent::where('company_id', $request->user()->company_id)->get(['id', 'first_name', 'last_name', 'agent_id']);
        // $pms = $request->user()->realEstateAgency()->agents()->get();
        return view('agent.application.create', compact('types', 'app', 'pms'));
    }


    /**
     * Display the specified resource.
     *
     * @param  \OnTheMove\Models\Application  $app
     * @return \Illuminate\Http\Response
     */
    public function show(Application $app = null, Request $request)
    {
        if (! $app) {
            return $this->showFromFlowbiz($request, $request->value('reference'));
        }

        return view('application.show', compact('app'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \OnTheMove\Models\Application  $app
     * @return \Illuminate\Http\Response
     */
    public function edit(Application $app)
    {
        if ($app->flowbiz_application_id) {
            flash('Application has already been provisioned.')->warning();

            return back()->withInput();
        }

        return view('application.edit', compact('app'));
    }


    protected function paginateSerach(Request $request, $data)
    {
        $currentPage = LengthAwarePaginator::resolveCurrentPage();
        $perPage = 15;

        // $currentItems = array_slice($data, $perPage * ($currentPage - 1), $perPage);


        // $items = array_reverse(array_sort($data, function ($value) {
        //     return $value['created_at'];
        // }));
        //$currentItems = array_slice($data, $perPage * ($currentPage - 1), $perPage);

        $paginator = new LengthAwarePaginator($data->forPage($currentPage, $perPage), $data->count(), $perPage, $currentPage, ['path' => route('agent.application.search')]);
        //$results = $paginator->appends('filter', request('filter'));

        // dump($paginator, $currentPage);
        // $collection = collect($collection);

        // $page = 1;
        // $perPage = 10;

        // $paginate = new LengthAwarePaginator($collection->forPage($page, $perPage), $collection->count(), $perPage, $page, ['path'=>url('api/products')]);

        //$apps = new LengthAwarePaginator($results, $results->count(), 25);

        return $paginator;
    }
}

resources/views/admin/applications/exception_match.blade.php
@extends('layouts.admin') 

@section('content')
<div class="container mt-6">

    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Failed Application</h4>
            <div class="card-options">
                
            </div>
        </div>
    
        <div class="card-body">
            <h2>{{ title_case($exception->type) }}</h2><br>
            <div class="row">
                <div class="col-6">
                    <form action="{{ route('admin.application.match', $exception, false) }}" method="POST">
                        @method('PATCH')
                        @csrf

                        @include('admin.applications.exceptions.' . snake_case($exception->type))
                      
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
                <div class="col-6">
                    <h4>Raw data provided:</h4>
                    <pre><code class="language-json">{{ json_encode(json_decode($exception->payload), JSON_PRETTY_PRINT) }}</code></pre>
                    <h4 class="mt-5">All data available:</h4>
                    <pre><code class="language-json">{{ json_encode(json_decode($app->toJson()), JSON_PRETTY_PRINT) }}</code></pre>
                </div>
            </div>
        </div>

        
    
</div>
</div>

@endsection

@section('foot')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/themes/prism-coy.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/prism.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-json.min.js"></script>
@endsection

resources/views/admin/applications/index.blade.php
@extends('layouts.admin')

@section('content')


<div class="container">
    <div class="row">

        <div class="col">
            <h1 class="ml-5 mb-4 mt-6">All Applications</h1>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Applications</h3>
                </div>
                <div class="table-responsive">
                    <table class="table card-table table-striped table-vcenter">
                        <thead>
                            <tr>
                                <th>Agency</th>
                                <th>Reference</th>
                                <th width="130">Status</th>  
                                <th>Address</th>
                                <th>Products</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($apps as $app)
                                @if(!$app->flowbiz_application_id)
                                    @continue
                                @endif
                            <tr>
                                 <td>
                                    {{$app->realEstateAgent()->first()->agency ?? 'N/A'}}<br>
                                    <small>{{$app->realEstateAgent()->first()->name ?? 'N/A'}}</small>
                                </td>
                                <td>
                                    @if($app->flowbiz_application_id)
                                         <a href="{{ route('admin.application.show', ['application' => $app], false) }}" class="text-underline">{{ $app->flowbiz_application_id }}</a>
                                    @else
                                         <span class='text-muted'>N/A</span>
                                    @endif
                                </td>
                                <td>
                                    <span class="status-icon bg-{{ $app->statusColor }}"></span>
                                    <small>{{ $app->flowbiz_application_status ?? "Not Submitted" }}</small>
                                </td>
                                <td><small>{{ $app->fullAddress }}</small></td>
                                <td>
                                 @foreach($app->services as $service)
                                <span class="tag tag-{{ $service->product->color }}">{{ $service->product->type }}</span>
                                 @endforeach
                                </td>
{{--                                 
                                <td>
                                   <i class="fe fe-info"></i>


                                {{-- <div class="item-action dropdown">
                                  <a href="javascript:void(0)" data-toggle="dropdown" class="icon" aria-expanded="false"><i class="fe fe-more-vertical"></i></a>
                                  <div class="dropdown-menu dropdown-menu-right" x-placement="top-end">
                                    <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-tag"></i> Action </a>
                                    <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-edit-2"></i> Another action </a>
                                    <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-message-square"></i> Something else here</a>
                                    <div class="dropdown-divider"></div>
                                    <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-link"></i> Separated link</a>
                                  </div>
                                </div> 
                                </td> --}}
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    {{ $apps->appends(request()->query())->links() }}
                </div>
            </div>
        </div>

    </div>
</div>

@endsection

resources/views/admin/applications/queue.blade.php
@extends('layouts.admin') 

@section('content')
<div class="container mt-6">

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Failed Application Queue</h4>
    </div>
    @if($apps->count())
    <div class="table-resposive">
        <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
            <thead>
                <tr>
                    <th>App</th>
                    <th>State</th>
                    <th>Issue</th>
                    <th colspan="2">Age</th>
                </tr>
            </thead>
            <tbody>
                @foreach($apps as $app)
                <tr>
                    <td>{{ $app->id }}</td>
                    <td class="{{ (!$app->state) ? 'text-muted' : '' }}">{{ $app->state ?? "N/A" }}</td>
                    <td>{{ title_case($app->type) }}</td>
                    <td>{{$app->created_at->diffForHumans() }}</td>
                    <td>
                       <a href="{{ route('admin.application.match', $app, false) }}" class="btn btn-secondary btn-sm">Fix Application</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @else
    <div class="card-body">
        <p class="p-6 text-center text-muted">No application waiting in queue</p>
    </div>
    @endif
</div>
</div>
@endsection